import Link from "next/link";
import type { ReactNode } from "react";
import { ArrowRight, BarChart3, FileCheck2, GitCompareArrows } from "lucide-react";

export default function Home() {
  return (
    <main className="landing-page">
      <section className="landing-hero">
        <div className="landing-copy">
          <span className="eyebrow">Tilo Framework · ROAM Loop</span>
          <h1>AI-native SaaS agents that render interfaces, observe actions, act safely, and memorize learning.</h1>
          <p>
            Tilo is not a chatbot wrapper. It turns a conversation into a task, a run, an interactive artifact, durable human decisions, and confirmed memory.
          </p>
          <div className="landing-actions">
            <Link className="primary-link" href="/workspace?demo=contract&autorun=1">
              Run Contract Review Demo
              <ArrowRight size={16} />
            </Link>
            <Link className="secondary-link" href="/workspace">
              Open ROAM Workspace
            </Link>
            <a className="secondary-link" href="https://github.com/adam2go/tilo-framework" target="_blank" rel="noreferrer">
              View GitHub
            </a>
          </div>
        </div>
        <div className="roam-preview" aria-label="ROAM product preview">
          {["Render", "Observe", "Act", "Memorize"].map((stage, index) => (
            <div className="preview-stage" key={stage}>
              <span>{index + 1}</span>
              <strong>{stage}</strong>
              <small>
                {stage === "Render" ? "Artifact surface" : null}
                {stage === "Observe" ? "UIInteractionEvent" : null}
                {stage === "Act" ? "Confirmation / Tool" : null}
                {stage === "Memorize" ? "Confirmed memory" : null}
              </small>
            </div>
          ))}
          <div className="preview-surface">
            <strong>Contract Review Surface</strong>
            <div className="preview-risk-row">
              <span>Liability</span>
              <em>high</em>
            </div>
            <div className="preview-risk-row">
              <span>Termination</span>
              <em>medium</em>
            </div>
            <button>Approve revision</button>
          </div>
        </div>
      </section>

      <section className="demo-entry-grid" aria-label="Demo entries">
        <DemoCard
          href="/workspace?demo=contract&autorun=1"
          icon={<FileCheck2 size={22} />}
          title="Contract Review"
          detail="Risk summary, review panel, approval card, editable draft placeholder, and memory candidate."
        />
        <DemoCard
          href="/workspace?demo=sales&autorun=1"
          icon={<BarChart3 size={22} />}
          title="Sales Follow-up"
          detail="Metric dashboard, action queue, tool preview, confirmation, and follow-up memory."
        />
        <DemoCard
          href="/workspace?demo=competitive&autorun=1"
          icon={<GitCompareArrows size={22} />}
          title="Competitive Analysis"
          detail="Comparison matrix, positioning selection, next-step queue, and reusable context."
        />
      </section>

      <section className="landing-section">
        <div>
          <span className="eyebrow">Why ROAM</span>
          <h2>Not a chat transcript. A generated workflow surface.</h2>
        </div>
        <div className="landing-explainer-grid">
          <ExplainerCard title="Render" detail="The agent renders contract review panels, approval cards, draft previews, and memory cards." />
          <ExplainerCard title="Observe" detail="Every meaningful click becomes a durable UIInteractionEvent, Confirmation, Feedback, or Memory event." />
          <ExplainerCard title="Act" detail="Approved actions can update artifacts, invoke tools, continue tasks, or create confirmation-gated next steps." />
          <ExplainerCard title="Memorize" detail="Only reviewed learning becomes inspectable long-term memory for future runs." />
        </div>
      </section>

      <section className="landing-section">
        <div>
          <span className="eyebrow">Interaction Components</span>
          <h2>Reusable SaaS primitives generated by agents.</h2>
        </div>
        <div className="component-chip-grid">
          {["RiskSummary", "RiskReviewPanel", "ApprovalCard", "EditableDocumentPreview", "MemoryCandidateCard", "ActionQueue", "ToolCallPreview"].map((item) => (
            <span key={item}>{item}</span>
          ))}
        </div>
      </section>

      <section className="landing-section architecture-band">
        <div>
          <span className="eyebrow">Developer Architecture</span>
          <h2>Conversation {"->"} Task {"->"} Run {"->"} Artifact {"->"} Observation {"->"} Memory.</h2>
        </div>
        <p>
          Tilo keeps backend primitives explicit: Task, Run, TraceStep, Artifact, Confirmation, UIInteractionEvent, Memory, Skill, and ToolInvocation.
        </p>
      </section>
    </main>
  );
}

function DemoCard({ href, icon, title, detail }: { href: string; icon: ReactNode; title: string; detail: string }) {
  return (
    <Link className="demo-entry-card" href={href}>
      <div className="demo-entry-icon">{icon}</div>
      <strong>{title}</strong>
      <span>{detail}</span>
      <small>
        Open demo
        <ArrowRight size={13} />
      </small>
    </Link>
  );
}

function ExplainerCard({ title, detail }: { title: string; detail: string }) {
  return (
    <article className="explainer-card">
      <strong>{title}</strong>
      <span>{detail}</span>
    </article>
  );
}
