#!/usr/bin/env python3
from __future__ import annotations

import re
import sys
from pathlib import Path


APP_ID_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]*$")


def main() -> int:
    if len(sys.argv) != 2 or sys.argv[1] in {"-h", "--help"}:
        print("Usage: scripts/create_app.py my-agent")
        return 0 if len(sys.argv) == 2 else 1

    app_id = sys.argv[1].strip()
    if not APP_ID_PATTERN.match(app_id):
        print("App id must use lowercase letters, numbers, and dashes.", file=sys.stderr)
        return 1

    repo_root = Path(__file__).resolve().parents[1]
    app_dir = repo_root / "examples" / "apps" / app_id
    if app_dir.exists():
        print(f"App already exists: {app_dir}", file=sys.stderr)
        return 1

    app_dir.mkdir(parents=True)
    title = app_id.replace("-", " ").title()
    (app_dir / "app.yaml").write_text(app_yaml(app_id, title), encoding="utf-8")
    (app_dir / "interaction.policy.yaml").write_text(policy_yaml(app_id), encoding="utf-8")
    (app_dir / "README.md").write_text(readme(app_id, title), encoding="utf-8")
    print(f"Created {app_dir.relative_to(repo_root)}")
    return 0


def app_yaml(app_id: str, title: str) -> str:
    return f"""id: {app_id}
version: "0.1"
name: {title}
description: Starter Tilo agent app.
entry:
  type: conversation
  default_prompt: Help me with this task.
runtime:
  model: default
  deterministic_fallback: true
  memory: enabled
  interaction_policy: interaction.policy.yaml
surfaces:
  mini:
    - MiniChoiceCard
    - MiniMemoryCard
  rich:
    - StarterArtifact
sample_inputs: []
tools: []
channels:
  - web
"""


def policy_yaml(app_id: str) -> str:
    return f"""id: {app_id}-policy
version: "0.1"
rules:
  - id: choose-next-step
    when:
      signal: next_step_needed
    decision: mini_surface
    surface: MiniChoiceCard
    reason: user_choice_needed
  - id: open-full-artifact
    when:
      user_action: open_full_review
    decision: rich_surface
    surface: StarterArtifact
    reason: explicit_escalation
"""


def readme(app_id: str, title: str) -> str:
    return f"""# {title}

Starter Tilo app generated by `scripts/create_app.py`.

Files:
- `app.yaml`
- `interaction.policy.yaml`

Next steps:
1. Edit the default prompt and description.
2. Keep only the mini surfaces your app actually needs.
3. Add a sample fixture if useful.
4. Verify with `GET /api/apps/{app_id}`.
"""


if __name__ == "__main__":
    raise SystemExit(main())
